version: "3"

services:
  dst-admin-go:
    image: hujinbo23/dst-admin-go:latest
    container_name: dst-admin-go
    ports:
      - "8082:8082"
      - "10998:10998/udp"
      - "10999:10999/udp"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./dstsave:/root/.klei/DoNotStarveTogether
      - ./dstsave/back:/app/backup
      - ./steamcmd:/app/steamcmd
      - ./dst-dedicated-server:/app/dst-dedicated-server
      - ./dstsave/dst-db:/app/dst-db
      - ./dstsave/password.txt:/app/password.txt
      - ./dstsave/first:/app/first
    restart: unless-stopped